# Generated by Django 3.2.7 on 2021-09-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(choices=[(1, 'เลือกเพศ'), (2, 'เพศชาย'), (3, 'เพศหญิง'), (4, 'เพศทางเลือก')]),
        ),
    ]
