# Generated by Django 3.2.7 on 2021-09-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
