# Generated by Django 3.2.7 on 2021-09-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(choices=[(0, 'เลือกเพศ'), (1, 'เพศชาย'), (2, 'เพศหญิง'), (3, 'เพศทางเลือก')], default=0),
        ),
    ]
