# Generated by Django 3.2.7 on 2021-09-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default='00', max_length=3, verbose_name='อายุ'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(choices=[(0, 'เลือกเพศ'), (1, 'เพศชาย'), (2, 'เพศหญิง'), (3, 'เพศทางเลือก')], default=0, verbose_name='เพศ'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pfirst_name',
            field=models.CharField(max_length=255, verbose_name='ชื่อจริง'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='plast_name',
            field=models.CharField(max_length=255, verbose_name='นามสกุล'),
        ),
    ]
