# Generated by Django 3.2.7 on 2021-09-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210911_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(default='', max_length=3, verbose_name='อายุ'),
        ),
    ]
