# Generated by Django 3.2.7 on 2021-09-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(choices=[(1, 'เพศชาย'), (2, 'เพศหญิง'), (3, 'เพศทางเลือก')], verbose_name='เพศ'),
        ),
    ]
