# Generated by Django 3.2.7 on 2021-09-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfirst_name', models.CharField(max_length=255, verbose_name='ชื่อจริง')),
                ('mlast_name', models.CharField(max_length=255, verbose_name='นามสกุล')),
                ('expertise', models.CharField(max_length=255, verbose_name='ความเชี่ยวชาญ')),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
    ]
