# Generated by Django 3.2.7 on 2021-09-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0015_auto_20210911_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfirst_name', models.CharField(max_length=255, verbose_name='ชื่อจริง')),
                ('mlast_name', models.CharField(max_length=255, verbose_name='นามสกุล')),
                ('expertise', models.CharField(max_length=255, verbose_name='ความเชี่ยวชาญ')),
            ],
            options={
                'verbose_name': 'Medic',
                'verbose_name_plural': 'Medics',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfirst_name', models.CharField(max_length=255, verbose_name='ชื่อจริง')),
                ('plast_name', models.CharField(max_length=255, verbose_name='นามสกุล')),
                ('gender', models.IntegerField(choices=[(1, 'เพศชาย'), (2, 'เพศหญิง'), (3, 'เพศทางเลือก')], verbose_name='เพศ')),
                ('age', models.CharField(default='', max_length=3, verbose_name='อายุ')),
                ('medic', models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='web.medic')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosname', models.CharField(max_length=50, verbose_name='ชื่อโรงพยาบาล')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.patient')),
            ],
        ),
    ]
