# Generated by Django 3.2.7 on 2021-09-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_hospital_medic_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
