# Generated by Django 3.2.7 on 2021-09-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
