# Generated by Django 3.2.7 on 2021-09-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20210911_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='affiliation',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='web.Hospital'),
        ),
    ]
